language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0.8

sudo: false

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "vendor"

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text
